name = "Jack Wu"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "Java开发工程师，全栈工程师."
company = "~"
location = "深圳"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.
