email = "jackwu1024@163.com"
#facebook = "yourfacebookusername"
github = "pangwawa"
#gitlab = "yourgitlabusername"
#linkedin = "yourlinkedinusername"
#stackoverflow = "yourstackoverflowuserid"
#twitter = "yourtwitterusername"
#weibo = "yourweibousername"
#zhihu = "yourzhihuusername"
#instagram = "yourinstagramusername"
#quora = "yourquorausername"
#tumblr = "yourtumblrusername"
#reddit = "yourredditusername"
#telegram = "yourtelegramusername"
qq = "2442591540"
#dockerhub = "yourdockerhubusername"
#bitbucket = "yourbitbucketworkspaceid"
#medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
#lastfm = "yourlastfmusername"
#bilibili = "yourbilibiliuserid"
