baseURL = "https://pangwawa.github.io/public"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "m10c"


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
  author = "John Doe"
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vehicula turpis sit amet elit pretium."
  menu_item_separator = " - "
  [[params.social]]
    name = "github"
    url = "https://github.com/gohugoio"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/gohugoio"
