baseURL = "https://pangwawa.github.io"
languageCode = "zh-Hans"
title = "小吴的工作手记"
theme = "m10c"
paginate = 10

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
  author = "Jack Wu"
  description = "互联网从业者，专注于Java架构、大数据开发"
  menu_item_separator = " - "
  [[params.social]]
    name = "github"
    url = "https://github.com/pangwawa"
  [[params.social]]
    name = "twitter"
    url = "https://blog.csdn.net/Jack__iT"

  # Brown theme
[params.style]
  darkestColor = "#242930"
  darkColor = "#353b43"
  lightColor = "#afbac4"
  lightestColor = "#ffffff"
  primaryColor = "#cc6258"